# 1.4.4 Smoothing Images

## Kernel Convolution

In [14]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [15]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [16]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [17]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [18]:
img

array([[4, 6, 6, 1, 9, 5, 2, 5, 7, 5, 5, 5],
       [3, 0, 0, 6, 9, 9, 3, 7, 4, 9, 3, 9],
       [5, 9, 7, 1, 7, 1, 9, 8, 8, 7, 3, 2],
       [9, 8, 8, 3, 6, 7, 8, 0, 3, 5, 2, 9],
       [6, 1, 5, 2, 1, 9, 9, 1, 9, 3, 9, 2],
       [4, 6, 3, 1, 6, 1, 2, 2, 1, 3, 7, 2],
       [8, 8, 8, 6, 6, 2, 8, 7, 5, 2, 3, 8],
       [8, 5, 6, 1, 4, 5, 1, 9, 1, 7, 7, 9],
       [1, 8, 5, 9, 2, 0, 0, 8, 4, 3, 0, 9],
       [6, 4, 7, 5, 2, 4, 3, 5, 9, 9, 4, 6],
       [6, 0, 6, 3, 1, 1, 8, 8, 5, 5, 4, 5],
       [9, 2, 8, 4, 5, 4, 5, 0, 2, 2, 1, 1]])

In [19]:
h,w=img.shape

In [20]:
print(h,w)

12 12


In [21]:
#[*range(-2,3)]

In [22]:
dst = np.zeros((h,w),np.int)

In [23]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [24]:
img

array([[4, 6, 6, 1, 9, 5, 2, 5, 7, 5, 5, 5],
       [3, 0, 0, 6, 9, 9, 3, 7, 4, 9, 3, 9],
       [5, 9, 7, 1, 7, 1, 9, 8, 8, 7, 3, 2],
       [9, 8, 8, 3, 6, 7, 8, 0, 3, 5, 2, 9],
       [6, 1, 5, 2, 1, 9, 9, 1, 9, 3, 9, 2],
       [4, 6, 3, 1, 6, 1, 2, 2, 1, 3, 7, 2],
       [8, 8, 8, 6, 6, 2, 8, 7, 5, 2, 3, 8],
       [8, 5, 6, 1, 4, 5, 1, 9, 1, 7, 7, 9],
       [1, 8, 5, 9, 2, 0, 0, 8, 4, 3, 0, 9],
       [6, 4, 7, 5, 2, 4, 3, 5, 9, 9, 4, 6],
       [6, 0, 6, 3, 1, 1, 8, 8, 5, 5, 4, 5],
       [9, 2, 8, 4, 5, 4, 5, 0, 2, 2, 1, 1]])

In [25]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -18, -19,  13,   5,  18, -15,   8, -15,  17, -14,   0],
       [  0,  16,  10, -19,  11, -28,  16,   8,  10,   3,  -2,   0],
       [  0,   5,   9,  -5,   6,   4,   7, -20, -10,   5, -18,   0],
       [  0, -21,   6,  -2, -19,  18,  16, -16,  28, -14,  22,   0],
       [  0,   8,  -8, -13,  15, -15, -12,  -3, -15,  -1,  11,   0],
       [  0,   5,   9,   8,   6, -12,  20,   4,   9, -10, -12,   0],
       [  0, -10,   5, -21,   2,  13, -18,  19, -21,  15,   9,   0],
       [  0,  17, -10,  23,  -7, -11, -12,  14,  -5,  -8, -23,   0],
       [  0,  -5,   8,  -1,  -4,  10,  -5,  -8,  13,  15,  -3,   0],
       [  0, -18,   6,  -4,  -7, -13,  15,  14,  -4,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [32]:
img = cv2.imread('lena.png', 0)

In [33]:
h,w=img.shape

In [34]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [35]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [36]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()