# 1.4.4 Smoothing Images

In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

## 2D Convolution (Image Filtering)

In [4]:
img = cv2.imread('.lena.png')
kernel = np.ones((5,5),np.float32)/25

In [5]:
kernel

array([[0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04]], dtype=float32)

In [6]:
dst = cv2.filter2D(img,-1,kernel)
plt.figure(figsize=(15,15))
plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(dst),plt.title('Averaging')
plt.xticks([]), plt.yticks([])
plt.show()

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\imgproc\src\filter.dispatch.cpp:1530: error: (-215:Assertion failed) !_src.empty() in function 'cv::filter2D'


# Image Blurring (Image Smoothing)

In [7]:
#blur = cv2.blur(img,(5,5))
blur = cv2.GaussianBlur(img,(5,5),0)
#blur = cv2.medianBlur(img,5)
#blur = cv2.bilateralFilter(img,9,75,75)
plt.figure(figsize=(15,15))
plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\imgproc\src\smooth.dispatch.cpp:620: error: (-215:Assertion failed) !_src.empty() in function 'cv::GaussianBlur'


## Kernel Convolution

In [8]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [9]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [10]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [11]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [12]:
img

array([[0, 1, 4, 8, 1, 9, 8, 1, 4, 4, 7, 8],
       [4, 6, 6, 7, 1, 3, 4, 8, 5, 5, 9, 3],
       [1, 0, 0, 2, 9, 5, 5, 9, 2, 3, 4, 1],
       [4, 6, 8, 0, 3, 6, 7, 0, 3, 6, 0, 2],
       [9, 6, 1, 2, 9, 1, 8, 6, 1, 7, 5, 4],
       [6, 2, 7, 0, 8, 0, 2, 9, 7, 3, 5, 5],
       [0, 2, 2, 1, 9, 6, 5, 3, 5, 2, 2, 1],
       [4, 9, 0, 6, 9, 1, 8, 6, 5, 4, 5, 2],
       [7, 6, 1, 3, 6, 7, 3, 2, 4, 4, 0, 4],
       [3, 6, 0, 0, 3, 7, 8, 5, 5, 5, 7, 9],
       [1, 4, 1, 3, 6, 2, 1, 9, 6, 9, 6, 0],
       [7, 2, 1, 6, 0, 1, 6, 0, 4, 3, 0, 2]])

In [13]:
h,w=img.shape

In [14]:
print(h,w)

12 12


In [15]:
#[*range(-2,3)]

In [16]:
dst = np.zeros((h,w),np.int)

In [17]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [18]:
img

array([[0, 1, 4, 8, 1, 9, 8, 1, 4, 4, 7, 8],
       [4, 6, 6, 7, 1, 3, 4, 8, 5, 5, 9, 3],
       [1, 0, 0, 2, 9, 5, 5, 9, 2, 3, 4, 1],
       [4, 6, 8, 0, 3, 6, 7, 0, 3, 6, 0, 2],
       [9, 6, 1, 2, 9, 1, 8, 6, 1, 7, 5, 4],
       [6, 2, 7, 0, 8, 0, 2, 9, 7, 3, 5, 5],
       [0, 2, 2, 1, 9, 6, 5, 3, 5, 2, 2, 1],
       [4, 9, 0, 6, 9, 1, 8, 6, 5, 4, 5, 2],
       [7, 6, 1, 3, 6, 7, 3, 2, 4, 4, 0, 4],
       [3, 6, 0, 0, 3, 7, 8, 5, 5, 5, 7, 9],
       [1, 4, 1, 3, 6, 2, 1, 9, 6, 9, 6, 0],
       [7, 2, 1, 6, 0, 1, 6, 0, 4, 3, 0, 2]])

In [19]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  13,   7,  11, -16,  -7,  -8,  13,   1,  -1,  17,   0],
       [  0, -13, -16,  -8,  25,  -3,  -5,  21, -12,  -5,   3,   0],
       [  0,   6,  25, -15, -12,   8,   9, -25,   3,  11, -17,   0],
       [  0,   6, -19,  -2,  22, -19,  16,   6, -19,  13,   4,   0],
       [  0, -13,  23, -18,  14, -17, -14,  18,  10,  -9,   5,   0],
       [  0,  -5,  -2, -13,  12,   9,   1, -13,   3,  -6,  -5,   0],
       [  0,  24, -18,  11,  14, -26,  17,   6,   1,   0,  12,   0],
       [  0,   1,  -5,  -1,   2,  11, -13, -10,   0,   3, -20,   0],
       [  0,  11,  -8,  -9,  -7,   8,  16,  -4,   0,  -5,   8,   0],
       [  0,   6,  -4,  -1,  16,  -7, -21,  24,  -3,  16,   8,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [20]:
img = cv2.imread('lena.png', 0)

In [21]:
h,w=img.shape

In [22]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [23]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [24]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()